### ISSUE TITLE
What is the size of the offset？

### ISSUE THREAD

**Issue by guoswang** [oeway/pytorch-deform-conv#14]
Hi,
I have read the paper“Deformable Convolutional Networks”and your pytoch-deform-conv code.
Then I think that the size of offset maybe b*c*kenel[0]*kenel[1]*h*w. Maybe I understand it wrong. Can you explain it?

**Comment by aurora95** [comment]
@guoswang I think you understand it correctly... This repo makes a wrong implementation

**Comment by oeway** [comment]
hi, @aurora95 thanks for your reminder. Unfortunately I don’t have time to
work on this right now.

However if you could give some more details about the issue, or ideally a
PR would be great for people who use this repo. Thanks.

Originally this repo is ported from the tensorflow implementation, I didn’t
any further analysis than the original repo.

**Comment by guoswang** [comment]
@aurora95 But I still want to say tha thanks for your great work !!
